version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: electron
    versions:
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.3.0
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.7.0
  - dependency-name: react-redux
    versions:
    - 7.1.3
    - 7.2.2
    - 7.2.3
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: babel-loader
    versions:
    - 8.1.0
  - dependency-name: eslint-config-airbnb
    versions:
    - 18.2.0
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: postcss-modules-values
    versions:
    - 3.0.0
  rebase-strategy: disabled
